### ISSUE TITLE
BPZ demo data in smoke test

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail#112]
**Bug report**
Need to add commands to smoke test for getting bpz data from NERSC

Otherwise, the newly moved in bpz notebooks fail:
- 'examples/estimation_examples/BPZ_lite_demo.ipynb'
- 'examples/estimation_examples/BPZ_lite_with_custom_SEDs.ipynb'

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by sschmidt23** [comment]
I think the commands are in the notebook, we just have them commented out by default because we didn't like the idea of having a notebook download data files when people just do a `run all cells` on a demo.  We can talk about whether it's ok to just uncomment the lines grabbing the extra files, if it's a blocker for the smoke tests I'd say we just do that.
